### ISSUE TITLE
Running the `crawl` subcommand without arguments causes a crash:

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/magellan#36]
Running the `crawl` subcommand without arguments causes a crash:
```
# ./magellan crawl 
{"level":"error","error":"endpoint must starts with http or https","time":"2024-07-01T14:21:53Z","message":"failed to connect to BMC"}
panic: endpoint must starts with http or https

goroutine 1 [running]:
github.com/OpenCHAMI/magellan/cmd.glob..func2(0xc0001fe400?, {0xccfac6?, 0x4?, 0xccfaca?})
	/opt/shared/magellan/cmd/crawl.go:22 +0x29f
github.com/spf13/cobra.(*Command).execute(0x14a5fe0, {0x15191a0, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x14a6b60)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/OpenCHAMI/magellan/cmd.Execute()
	/opt/shared/magellan/cmd/root.go:51 +0x1a
main.main()
	/opt/shared/magellan/main.go:8 +0xf
```
Perhaps it would be better to have the BMC URI be a positional argument rather than a flag.

_Originally posted by @synackd in https://github.com/OpenCHAMI/magellan/issues/34#issuecomment-2200301201_

**Comment by davidallendj** [comment]
Either that or `MarkFlagRequired` might work. Positional arguments would probably make more sense here though.

**Comment by synackd** [comment]
Not sure if this is the same issue, but I'm getting the same error even when passing a valid URL:
```
# ./magellan crawl -i -u https://172.16.0.105/redfish/v1 -u <username> -p '<password>'
{"level":"error","error":"endpoint must starts with http or https","time":"2024-07-01T14:54:02Z","message":"failed to connect to BMC"}
panic: endpoint must starts with http or https

goroutine 1 [running]:
github.com/OpenCHAMI/magellan/cmd.glob..func2(0xc0001fe400?, {0xccfac6?, 0x4?, 0xccfaca?})
	/opt/shared/magellan/cmd/crawl.go:22 +0x29f
github.com/spf13/cobra.(*Command).execute(0x14a5fe0, {0xc0001f4770, 0x7, 0x7})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x14a6b60)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/OpenCHAMI/magellan/cmd.Execute()
	/opt/shared/magellan/cmd/root.go:51 +0x1a
main.main()
	/opt/shared/magellan/main.go:8 +0xf
```
I can reach the endpoint fine with cURL:
```
# curl -o /dev/null -s -w "%{http_code}\n" -k https://172.16.0.105/redfish/v1
200
```

**Comment by alexlovelltroy** [comment]
Your second comment underscores how bad the first bug was.  Before I moved the uri to the argument, "-u" was URI and "-n" was username.  You tried "-u" for both which can't work, but is intuitive.  Please try the linked branch and let me know what you think.

**Comment by synackd** [comment]
> Your second comment underscores how bad the first bug was. Before I moved the uri to the argument, "-u" was URI and "-n" was username. You tried "-u" for both which can't work, but is intuitive. Please try the linked branch and let me know what you think.

Will do. Can you link the branch?

**Comment by synackd** [comment]
Oh whoops, yes I see that I did `-u` twice instead of `-n` for the username in the second comment...

**Comment by alexlovelltroy** [comment]
https://github.com/OpenCHAMI/magellan/tree/36-running-the-crawl-subcommand-without-arguments-causes-a-crash

Should also be in the header/sidebar of this issue

**Comment by synackd** [comment]
On that branch, I rightfully get a 401 Unauthorized without a token, but it is still crashing:
```
# ./magellan crawl -i -u <username> -p '<password>' 'https://172.16.0.105/redfish/v1'
{"level":"error","error":"401: Unauthorized","time":"2024-07-01T17:00:02Z","message":"failed to connect to BMC"}
panic: 401: Unauthorized

goroutine 1 [running]:
github.com/OpenCHAMI/magellan/cmd.glob..func3(0xc0001fe400?, {0xc000076900, 0x1, 0xccfbe7?})
	/opt/shared/magellan/cmd/crawl.go:34 +0x295
github.com/spf13/cobra.(*Command).execute(0x14a5fe0, {0xc0000768a0, 0x6, 0x6})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x14a6b60)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/OpenCHAMI/magellan/cmd.Execute()
	/opt/shared/magellan/cmd/root.go:51 +0x1a
main.main()
	/opt/shared/magellan/main.go:8 +0xf
```

**Comment by synackd** [comment]
Do I need a token if I'm just printing the system info without contacting SMD?

**Comment by alexlovelltroy** [comment]
crawl doesn't interact with smd at all.  It just pulls relevant data from the BMC and spits out json.

**Comment by synackd** [comment]
I don't know why I am getting 401 Unauthorized then. I can curl with the credentials I am passing just fine:
```
# curl -k https://172.16.0.105/redfish/v1/Systems/
Unauthorized
# curl -u '<username>:<password>' -k https://172.16.0.105/redfish/v1/Systems/
{
  "@odata.id": "/redfish/v1/Systems",
  "@odata.type": "#ComputerSystemCollection.ComputerSystemCollection",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/system"
    }
  ],
  "Members@odata.count": 1,
  "Name": "Computer System Collection"
}
```

**Comment by alexlovelltroy** [comment]
Try again with the updated branch using the following command:
`./magellan crawl https://172.16.0.105/`

**Comment by synackd** [comment]
No crashes this time:
```
# ./magellan crawl -i -u <username> -p '<password>' 'https://172.16.0.105/'
{"level":"error","error":"authentication failed.  Check your username and password: https://172.16.0.105/","time":"2024-07-01T18:07:27Z","message":"failed to connect to BMC"}
2024/07/01 18:07:27 Error crawling BMC: authentication failed.  Check your username and password: https://172.16.0.105/
```
Doing the command you mentioned verbatim yields a TLS error, which is expected:
```
# ./magellan crawl 'https://172.16.0.105/'
{"level":"error","error":"Get \"https://172.16.0.105//redfish/v1/\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-07-01T18:07:46Z is after 1979-12-30T00:00:33Z","time":"2024-07-01T18:07:46Z","message":"failed to connect to BMC"}
2024/07/01 18:07:46 Error crawling BMC: Get "https://172.16.0.105//redfish/v1/": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-07-01T18:07:46Z is after 1979-12-30T00:00:33Z
```

**Comment by davidallendj** [comment]
I think it should probably be made clearer that this is expecting the BMC host and not the Redfish root endpoint.

**Comment by synackd** [comment]
Removing `/redfish/v1` fixed it.
